// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://piklzelulcyzvaprwuec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpa2x6ZWx1bGN5enZhcHJ3dWVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5Mjk5MzEsImV4cCI6MjA1NTUwNTkzMX0.cqDtsrqRjYgILthwtzf3FDuryTarzoSt3uThaxwZ0D8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);